name = "alpha-panel"
main = "src/index.js"
compatibility_date = "2026-09-24"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "alpha-db"
database_id = "bfcc3dd2-42d4-4042-b110-9d37c3a4685e"
migrations_dir = "migrations"

[vars]
ALPHA_CHANNEL = "@V2rayTun0"
ALPHA_AUTHOR = "@Mehtif"
[triggers]
crons = ["0 * * * *"]
