ALTER TABLE nodes ADD COLUMN maintenance_mode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN drain_mode INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN weight INTEGER NOT NULL DEFAULT 100;
ALTER TABLE nodes ADD COLUMN capacity INTEGER NOT NULL DEFAULT 0;
ALTER TABLE nodes ADD COLUMN tags TEXT NOT NULL DEFAULT '[]';
ALTER TABLE nodes ADD COLUMN notes TEXT NOT NULL DEFAULT '';
CREATE INDEX IF NOT EXISTS idx_nodes_ops ON nodes(maintenance_mode,drain_mode,status);
